@baseUrl = http://localhost:8000/api
@contentType = application/json

### Create Plan
POST {{baseUrl}}/plans
Content-Type: {{contentType}}

{
    "name": "Basic Plan",
    "photoLimit": 5,
    "musicAllowed": false,
    "customization": {
        "fonts": ["Arial", "Times New Roman"],
        "colors": ["#000000", "#FFFFFF"]
    },
    "expiryDuration": "1 year",
    "price": 9.99
}

### Get all plans
GET {{baseUrl}}/plans
Content-Type: {{contentType}}

### Get plan by ID
GET {{baseUrl}}/plans/1
Content-Type: {{contentType}} 